### 계좌 생성
POST http://localhost:8080/api/v1/account
Content-Type: application/json

{
  "userId": 68
}

### 계좌 잔액 조회
GET http://localhost:8080/api/v1/account/balance
Content-Type: application/json

{
  "accountId": 72
}

### 계좌 입금
POST http://localhost:8080/api/v1/account/deposit
Content-Type: application/json

{
  "accountId": 73,
  "amount": 1000
}

### 계좌 출금
POST http://localhost:8080/api/v1/account/withdraw
Content-Type: application/json

{
  "accountId": 72,
  "amount": 1000
}

### 계좌 송금
POST http://localhost:8080/api/v1/account/transfer
Content-Type: application/json

{
  "fromAccountId": 73,
  "toAccountId": 72,
  "amount": 1000
}

### 계좌 삭제
DELETE http://localhost:8080/api/v1/account
Content-Type: application/json

{
  "accountId": 72
}