### 계좌 생성
POST http://localhost:8080/api/v1/account
Content-Type: application/json

{
  "userId": 1
}

### 계좌 잔액 조회
GET http://34.47.68.121:8080/api/v1/account/balance
Content-Type: application/json

{
  "accountNumber": "mj-user00"
}

### 계좌 입금
POST http://34.47.68.121:8080/api/v1/account/deposit
Content-Type: application/json

{
  "accountNumber": "mj-user00",
  "amount": 1000
}

### 계좌 출금
POST http://localhost:8080/api/v1/account/withdraw
Content-Type: application/json

{
  "accountNumber": 30255492,
  "amount": 1000
}

### 계좌 송금
POST http://34.64.125.6:8080/api/v1/account/transfer
Content-Type: application/json

{
  "fromAccountNumber": "mj82227053",
  "toAccountNumber": "jh-USER0ACCOUNT0",
  "amount": 500
}

### 계좌 삭제
DELETE http://localhost:8080/api/v1/account
Content-Type: application/json

{
  "accountNumber": 72
}


### 유저의 전체 계좌정보 조회
GET http://34.47.68.121:8080/api/v1/account/accountInfos
Content-Type: application/json

{
  "userId": 1
}

### 계좌의 기간별 거래내역 조회
GET http://13.124.221.0:8080/api/v1/account/recordByPeriod
Content-Type: application/json

{
  "accountNumber": 77960076,
  "startDate": "2024-01-01",
  "endDate": "2024-05-31"
}
